import React from 'react';
import Head from 'next/head';
import styles from '../styles/index.module.scss';

class Home extends React.Component {
  constructor(props: any) {
    super(props);
  }

  render = () => (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
      </main>
    </div>
  );
}

export default Home;
